In [12]:
import numpy as np

bias = 187500.02235174447

path = "./best_data_right/OpenBCI-RAW-2024-03-02_15-16-08.txt"

file = open(path, mode="r").readlines()

data = []

for line in file:
    if "%" not in line:
        results = line.rstrip().split(", ")
        data.append([results[0], results[3], results[6]])

for d in range(1, len(data)):
    data[d] = [float(data[d][0]), (float(data[d][1]) + bias) / 1000, (float(data[d][2]) + bias) / 1000]

data = np.array(data[1::], dtype=np.float64)\

print(data)

np.savetxt("right1.npy", data)

[[  0.          19.0888815   17.04539562]
 [  1.          18.80680249  16.83291994]
 [  2.          19.52865208  17.59958477]
 ...
 [225.          18.20437827  16.21677175]
 [226.          18.76203194  16.75381711]
 [227.          18.42195015  16.35892884]]
